import {
  AlertTriangle,
  ArrowRight,
  Check,
  ChevronLeft,
  ChevronRight,
  Command,
  CreditCard,
  File,
  FileText,
  HelpCircle,
  Image,
  Laptop,
  LayoutDashboard,
  Loader2,
  LogIn,
  Moon,
  MoreVertical,
  Plus,
  Settings,
  Sun,
  Trash,
  User,
  UserCircle,
  UserX,
  X,
  LayoutGrid,
  Github,
  Folder,
  Users,
  Crown,
  Star,
  Box,
  ShoppingBag,
  Building2,
  Package,
  ClipboardList,
  Clock,
  CheckCircle,
  Shield,
  type LucideIcon,
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  dashboard: LayoutDashboard,
  logo: Command,
  login: LogIn,
  close: X,
  product: Box,
  spinner: Loader2,
  kanban: LayoutGrid,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  trash: Trash,
  employee: UserX,
  post: FileText,
  page: File,
  userPen: User,
  user2: UserCircle,
  media: Image,
  settings: Settings,
  billing: CreditCard,
  ellipsis: MoreVertical,
  add: Plus,
  warning: AlertTriangle,
  user: User,
  arrowRight: ArrowRight,
  help: HelpCircle,
  sun: Sun,
  moon: Moon,
  laptop: Laptop,
  github: Github,
  check: Check,
  workspace: Folder,
  teams: Users,
  pro: Crown,
  exclusive: Star,
  account: UserCircle,
  profile: User,
  // Custom icons for Selfy
  shoppingBag: ShoppingBag,
  building: Building2,
  package: Package,
  clipboard: ClipboardList,
  clock: Clock,
  checkCircle: CheckCircle,
  shield: Shield,
};

